fn do_sth_that_might_fail(iL i32) -> Result<f32, String>{
    if i ==42 {
	Ok(13.0)
    } else {
	Err(String::from("this is not the right number"))
    }
}

fn main() -> Result<(), String> {
    let v = do_sth_that_might_fail(42).unwrap();
    println!("found {}", v);

    let v = do_sth_that_might_fail(1).unwrap();
    println!("found {}", v);

    Ok(())
}
